#!/bin/bash
module load GMT

# Define the names of the input and output files =======================================================
out="LA_seis.ps"                          # This will be the name of your map generated by this file
seis_data="LosAngeles_SECDC.txt"          # ANSS earthquake catalog
topo="ladem.grd"                          # GMRT 61 m resolution topography grid
demcpt="DEM_poster.cpt"                   # Color palette for the topography (DEM)

# Define map area (the bounding box) ===================================================================
north=34.2
south=33.4
east=-117.5
west=-118.7

# Define your map boundary annotation ==================================================================
tick='-B0.2/0.2WSen'

# Define Map Projection ================================================================================
proj='-JM15'

# Make color palettes ==================================================================================
makecpt -C$demcpt -T0/1800/50 -Z  > topo.cpt
makecpt -Chot -T10/30/2 -I > seis.cpt

# Plot the base topography, seismicity in the area =====================================================
psbasemap -R$west/$east/$south/$north $proj $tick -P -Y12 -K > $out
grdgradient $topo -A135 -Ne0.4 -Gshadow.grd
grdimage $topo -R -J -O -K -Ctopo.cpt -Ishadow.grd >> $out
psscale -D15.5/3.2/5/0.5 -B500:Height:/:m: -Ctopo.cpt -O -K >> $out
pscoast -R -J -O -K -W1 -Df -Na -Ia -S135/206/250 -Lf-118.45/33.58/10/20+lkm >> $out
psxy -R -J -O -K $seis_data -Wfaint -i7,6,8,4ls0.8 -Sc -h1 -Cseis.cpt >> $out
psxy -R -J -O -K stationslist.txt -W1 -G1 -St6p >> $out
awk '{print $1-0.02, $2-0.02, $3}' stationslist.txt | pstext -R -J -O -K >> $out
psscale -D15.5/9/3/0.5 -B10:Depth:/:km: -Cseis.cpt -O -K >> $out

# Define a profile for cross-section view ==============================================================
ax=-118.4   # Start point longitute
ay=34       # Start point latitute
bx=-117.8   # End point longitute
by=33.7     # End point latitute

# Draw the pofile on the map ===========================================================================
psxy -R -J -O -K -W1 -Sc.1 -G20 << EOF >> $out
$ax $ay
$bx $by 
EOF
psxy -R -J -O -K -W1,20 << EOF  >> $out
$ax $ay
$bx $by 
EOF

# Project the seismicity on the profile ================================================================
awk 'NR>1 && NR<41 {print $8, $7, $9, $5}' LosAngeles_SECDC.txt > seis.txt 
    # <seis.txt> file format: Lon., Lat., Depth, Magnitute (for scaling)
project seis.txt -C$ax/$ay -E$bx/$by -W-40/40 -Q > projection.dat
    # -C<startpoint> -E<endpoint> -W<width(km)> -Q<unit in km>

# Plot the profile in a new subplot ====================================================================
proj=-JX15/-5
tick=-B10:Distance:/10:Depth:WSen
psxy projection.dat -i4,2,2,3ls1.0 -R0/65/0/30 $proj $tick -Wfaint -Sc -Cseis.cpt -O -Y-8 -P >> $out


# Output file and show it ==============================================================================
ps2pdf $out
gv $out
